version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
      - "/initialize-variables"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"
    labels:
      - "part: github_actions"
